In [1]:
import csv
import pandas as pd

In [2]:
df = pd.read_csv('../craw-data/raw-data/item-data/data0.csv')

In [3]:
df

,itemid,shopid,userid,price_max_before_discount,has_lowest_price_guarantee,price_before_discount,price_min_before_discount,exclusive_price_info,hidden_price_display,price_min,...,flash_sale,upcoming_flash_sale,deep_discount,has_low_fulfillment_rate,is_partial_fulfilled,makeups,shop_vouchers,global_sold,is_infant_milk_formula_product,topic
0,3786337916,140586149,0,-1,False,0,-1,NaN,NaN,4500000000,...,NaN,NaN,NaN,False,True,NaN,NaN,NaN,False,11035567
1,4940639962,259983656,0,16800000000,False,9900000000,9900000000,NaN,NaN,9900000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567
2,8720325948,375004204,0,37500000000,False,37500000000,37500000000,NaN,NaN,32500000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567
3,8620325944,375004204,0,67500000000,False,67500000000,67500000000,NaN,NaN,36500000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567
4,9343353763,252644662,0,-1,False,0,-1,NaN,NaN,3500000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8032,1594322863,97206240,0,17900000000,False,17900000000,17900000000,NaN,NaN,9900000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567
8033,3548630241,71009635,0,-1,False,0,-1,NaN,NaN,35000000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567
8034,7783686027,94065732,0,15000000000,False,15000000000,15000000000,NaN,NaN,10800000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567
8035,1598870922,28487044,0,-1,False,0,-1,NaN,NaN,16500000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567
8036,97948385,4026185,0,13000000000,False,6500000000,6500000000,NaN,NaN,4500000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11035567

In [5]:
list_data = df.T.to_dict().values()

In [8]:
from kafka import KafkaProducer
from json import dumps
kafka_producer = KafkaProducer(bootstrap_servers='localhost:9092', value_serializer=lambda x: dumps(x).encode('utf-8'))

In [9]:
for item in list_data:
    kafka_producer.send('item-shopee', value=item)